### PR TITLE
Added pings

### PR DESCRIPTION
**Pull request by DarkIntaqt**
- Added the pings to types and structures
- Ran format and lint
- Regenerated the documentation
- Ran tests with 100% coverage

### CODE REVIEW

**Review by TheDrone7 — CHANGES_REQUESTED** [review]
1. A PR should not update the version.
2. Modification of the package.json should be a separate PR.
3. Looks good otherwise.

**Comment by DarkIntaqt** [comment]
> 1. A PR should not update the version.
Oh well I was once told (not by you) "WHY HAVENT YOU CHANGED THE VERSION", so I was a bit confused. Won't happen again. I have removed the changes requested from this PR

**Comment by DarkIntaqt** [comment]
Btw, might be a bit off-topic but it seems like the GitHub checks are failing due to a wrong/invalid API-key

**Comment by TheDrone7** [comment]
Ye I keep the API key incorrect until I verify the files for possible key leaks and then rerun with the correct API key.

**Comment by TheDrone7** [comment]
> > 1. A PR should not update the version.
> 
> Oh well I was once told (not by you) "WHY HAVENT YOU CHANGED THE VERSION", so I was a bit confused. Won't happen again. I have removed the changes requested from this PR

Must've been before v1 for sure.

**Comment by DarkIntaqt** [comment]
So should I actually create another PR for the packagejson change or do you just want to do it with a quick commit on your site? I mean its just changing a single link

**Comment by TheDrone7** [comment]
Either way works

**Review by TheDrone7 — APPROVED** [review]
Looks good (if the tests pass)

**Comment by DarkIntaqt** [comment]
> Either way works

Ok, then feel free to quickly change this. I currently don't have the time to do this. 
Thanks for merging :)

**Pull request merged**
